/*
 * Copyright (C) 2026 Jimvixx
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.jimvixx.smsecure.jobs;

import android.content.Context;
import org.jimvixx.smsecure.logging.Log;
import org.junit.Test;
import org.mockito.MockedStatic;
import org.whispersystems.jobqueue.Job;
import java.io.IOException;
import java.util.Arrays;
import java.util.HexFormat;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class StableJobCodecTest {
  private final Context context = mock(Context.class);

  @Test public void sendFixtureKeepsAttemptAndGroupAcrossRestarts() throws Exception {
    // Fixed v1 bytes are a compatibility contract, not generated by the encoder under test.
    byte[] fixture = HexFormat.of().parseHex(
        "000000010008736d735f73656e64000000000000002a01000567726f7570010007617474656d7074");
    SmsSendJob send = (SmsSendJob)StableJobCodec.decode(context, fixture);
    assertEquals(42, send.messageId);
    assertEquals("attempt", send.sendAttemptId);
    assertEquals("group", send.getGroupId());
    assertEquals(15, send.getRetryCount());
    assertEquals(2, send.getRequirements().size());
    assertArrayEquals(fixture, StableJobCodec.encode(send));
    SmsSendJob second = (SmsSendJob)StableJobCodec.decode(context, StableJobCodec.encode(send));
    assertEquals(send.sendAttemptId, second.sendAttemptId);
  }

  @Test public void receiveFixturePreservesInternalSimIdAndRawPdus() throws Exception {
    byte[] fixture = HexFormat.of().parseHex(
        "00000001000b736d735f726563656976650000007b000000020000000301020300000001ff");
    SmsReceiveJob receive = (SmsReceiveJob)StableJobCodec.decode(context, fixture);
    assertEquals(123, receive.subscriptionId);
    assertArrayEquals(new byte[]{1,2,3}, (byte[])receive.pdus[0]);
    assertArrayEquals(new byte[]{(byte)255}, (byte[])receive.pdus[1]);
    assertTrue(receive.needsWakeLock());
    assertArrayEquals(fixture, StableJobCodec.encode(receive));
    verifyNoInteractions(context);
  }

  @Test public void otherPersistentJobsRoundTripWithoutRunning() throws Exception {
    try (MockedStatic<Log> ignored = mockStatic(Log.class)) {
      SmsDecryptJob decrypted = (SmsDecryptJob)roundTrip(new SmsDecryptJob(context, 81, true, true));
      assertEquals(81, decrypted.messageId);
      assertTrue(decrypted.manualOverride);
      assertTrue(decrypted.isReceivedWhenLocked);
      SmsSentJob sent = (SmsSentJob)roundTrip(new SmsSentJob(context, 92, "sent-action", -1));
      assertEquals(92, sent.messageId);
      assertEquals("sent-action", sent.action);
      assertEquals(-1, sent.result);
      assertTrue(roundTrip(new GenerateKeysJob(context)) instanceof GenerateKeysJob);
    }
  }

  @Test public void malformedAndFutureRecordsAreRejected() throws Exception {
    byte[] valid = StableJobCodec.encode(new GenerateKeysJob(context));
    byte[] future = valid.clone();
    future[3] = 2;
    assertThrows(IOException.class, () -> StableJobCodec.decode(context, future));
    assertThrows(IOException.class, () -> StableJobCodec.decode(context, Arrays.copyOf(valid, 3)));
    assertThrows(IOException.class, () -> StableJobCodec.decode(context, Arrays.copyOf(valid, valid.length + 1)));
    byte[] badCount = HexFormat.of().parseHex("00000001000b736d735f72656365697665000000017fffffff");
    assertThrows(IOException.class, () -> StableJobCodec.decode(context, badCount));
    assertThrows(IOException.class, () -> StableJobCodec.encode(mock(Job.class)));
  }

  @Test public void deliveryReportKeepsAttemptPartAndArrivalTime() throws Exception {
    SmsSentJob sent = new SmsSentJob(context, 42, 69, "attempt", 1, 3, 123456);
    SmsSentJob restored = (SmsSentJob)roundTrip(sent);
    assertEquals(69, restored.result);
    assertEquals("attempt", restored.deliveryAttempt);
    assertEquals(1, restored.deliveryPart);
    assertEquals(3, restored.deliveryParts);
    assertEquals(123456, restored.deliveryReceivedAt);
  }

  private Job roundTrip(Job job) throws Exception {
    Job result = StableJobCodec.decode(context, StableJobCodec.encode(job));
    assertTrue(result.isPersistent());
    assertEquals(job.getRequirements().size(), result.getRequirements().size());
    return result;
  }
}
