version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - gradle
    ignore:
      - dependency-name: "com.android.application"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies