android.useAndroidX=true
android.enableJetifier=false

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=true
org.gradle.caching=true

whisperSonatypeUsername=
whisperSonatypePassword=
sonatypeRepo=/dev/null

VERSION_NAME=
VERSION_CODE=
GROUP=
POM_DESCRIPTION=
POM_URL=
POM_SCM_URL=
POM_SCM_CONNECTION=
POM_SCM_DEV_CONNECTION=
POM_LICENCE_NAME=
POM_LICENCE_URL=
POM_LICENCE_DIST=
POM_DEVELOPER_ID=
POM_DEVELOPER_NAME=

